const URL='https://fhjutbhyvaamzzsipwaa.supabase.co';
const KEY='sb_publishable_Ytbw_MTkDIhZP1KerZ4bAw_P7XPwFH_';
const db=window.createAtlasClient(URL,KEY);
window.addEventListener('error',e=>{
  const el=document.getElementById('authMessage');
  if(el) el.textContent='Atlas startup error: '+(e.message||'unknown error');
});
const $=id=>document.getElementById(id);
let authMode='signup',user=null,profile=null,subjects=[],concepts=[],states=[],sessions=[],attempt=null,round=1,qIndex=0,answers=[],roundQs=[],openIndex=0,todayDone=new Set(),frontierConcept=null;
const VIEWS=['auth','onboarding','assessmentIntro','assessment','checkpoint','app'];
const EXTRA=['Science','Health & Medicine','Trades & Construction','Business & Leadership','Accounting & Economics','Technology & AI','History & Geopolitics','Psychology & Philosophy','Arts & Culture'];

const A=[
['a_reason','reasoning',2,'A city finds that neighborhoods with more fire trucks have more fire damage. Best interpretation?',['Fire trucks cause damage','Larger fires cause both more trucks and more damage','The data proves nothing','Fire damage is random'],1],
['a_math','mathematics',2,'A $240 bill is reduced by 15%. What is the new total?',['$204','$215','$225','$230'],0],
['a_stats','statistics',2,'A poll samples only volunteers from one news website. Main concern?',['Selection bias','Too much randomization','A larger sample','No opinions can be measured'],0],
['a_phys','physics',2,'A car moves around a circular track at constant speed. Is it accelerating?',['No','Yes, direction changes','Only downhill','Only if engine speed rises'],1],
['a_chem','chemistry',2,'What determines which element an atom is?',['Number of protons','Its size','Temperature','Number of molecules'],0],
['a_bio','biology',2,'Genes are best described as…',['Segments of DNA containing biological instructions','Whole organs','Types of bacteria','Free proteins'],0],
['a_med','medicine',2,'Why do ordinary antibiotics generally not treat viral infections?',['Viruses have no mass','Antibiotics target bacterial processes','Viruses exist only in blood','Antibiotics remove oxygen'],1],
['a_health','health_wellness',2,'Why is regular sleep broadly important?',['It replaces exercise','It supports cognition, metabolism, immunity, and recovery','It guarantees no illness','It permanently lowers heart rate'],1],
['a_hist','history',2,'Which occurred first?',['Industrial Revolution','Ancient Greece','World War I','Cold War'],1],
['a_geo','geography',2,'Why did many early civilizations grow near rivers?',['Water, fertile soil, transport, and trade','Rivers prevented wars','Only religious reasons','Rivers made climates identical'],0],
['a_econ','economics',2,'Demand rises while supply stays fixed. Price normally…',['Falls','Usually rises','Must stay fixed','Becomes zero'],1],
['a_gov','government',2,'The U.S. Congress consists of…',['House and Senate','President and Court','States and counties','Cabinet and Senate'],0],
['a_comp','computing',2,'RAM is mainly used for…',['Permanent archives','Temporary working data for active programs','Internet routing only','Cooling the CPU'],1],
['a_phil','philosophy',2,'Which is an objective claim?',['This painting is beautiful','The room is 72°F','Jazz is better than rock','Summer is nicest'],1],
['a_cult','culture_society',2,'A good first step in studying another culture is to…',['Assume your norms are universal','Understand practices in historical/social context','Treat all members as identical','Judge only by popularity'],1]
];
const HARD={
reasoning:['h_reason','reasoning',6,'A randomized controlled trial strengthens causal inference mainly because…',['Random assignment reduces systematic confounding','The treatment costs money','The sample has opinions','It was published online'],0],
mathematics:['h_math','mathematics',6,'Solve x² − 5x + 6 = 0.',['1 or 6','2 or 3','−2 or −3','5 only'],1],
statistics:['h_stats','statistics',6,'A rare disease test is 95% sensitive and 95% specific. Why can many positive tests still be false positives?',['Base rates matter','Sensitivity becomes zero','Specificity only applies to treatment','Probability cannot model rare events'],0],
physics:['h_phys','physics',6,'Astronauts in orbit appear weightless mainly because…',['Gravity is zero','They and the spacecraft are continuously falling','Air pressure cancels gravity','The Moon blocks gravity'],1],
chemistry:['h_chem','chemistry',6,'In an ordinary chemical reaction, what primarily changes?',['Atomic nuclei split routinely','Electrons and bonding arrangements','Protons become electrons','Matter disappears'],1],
biology:['h_bio','biology',6,'Which sequence is accurate?',['Protein → gene → DNA','DNA contains genes; genes can encode proteins','Genes contain cells','DNA is only protein'],1],
medicine:['h_med','medicine',6,'Why can a highly sensitive screening test still need confirmation?',['False positives can occur, especially when prevalence is low','Sensitivity means all positives are true','All screening measures blood pressure','Confirmation is always legally required'],0],
health_wellness:['h_health','health_wellness',6,'Which bundle most reliably improves cardiovascular risk across populations?',['Activity, smoking reduction, BP control, healthy diet patterns','Supplements instead of movement','Avoiding all dietary fat','Four hours sleep'],0],
history:['h_hist','history',6,'Major long-term causes of World War I included…',['Alliances, militarism, nationalism, imperial rivalry','Only invasion of Poland','Only the Depression','Only Reformation'],0],
geography:['h_geo','geography',6,'Why can a maritime chokepoint matter geopolitically?',['It can constrain trade and military movement','It changes gravity','It guarantees crops','It removes currency risk'],0],
economics:['h_econ','economics',6,'A central bank raises policy rates substantially. Typical effect?',['Credit gets cheaper','Borrowing gets costlier and demand may cool','Money becomes infinite','All wages fall automatically'],1],
government:['h_gov','government',6,'Judicial review means courts can…',['Write budgets','Evaluate government actions against the Constitution','Command the military','Elect senators'],1],
computing:['h_comp','computing',6,'DNS primarily…',['Translates domain names to network addresses','Encrypts every file','Replaces CPUs','Measures speed only'],0],
philosophy:['h_phil','philosophy',6,'Occam’s razor is best understood as…',['Simplest is always true','Prefer fewer unsupported assumptions when evidence is comparable','Complex is always false','Majorities determine truth'],1],
culture_society:['h_cult','culture_society',6,'Studying culture contextually means…',['Understanding practices in their social/historical setting before evaluating them','Assuming all cultures are identical','Ignoring internal diversity','Treating norms as genetic'],0]
};
const EASY=A.map(x=>[x[0]+'_e',x[1],2,x[3],x[4],x[5]]);
const R3=[
['r_fit','physical_health',4,'Progressive overload means…',['Gradually increasing training demand as capacity improves','Doing less each week','Never recovering','Only gaining body weight'],0],
['r_fin','finance',4,'A bond is…',['Ownership in a company','A debt instrument issued to investors','An insurance policy','A checking account'],1],
['r_acct','accounting',4,'The accounting equation is…',['Assets = Liabilities + Equity','Revenue = Assets + Debt','Cash = Profit + Taxes','Equity = Revenue − Customers'],0],
['r_law','law',4,'Burden of proof refers to…',['Responsibility to establish a claim to the required standard','Number of judges','Cost of a lawyer','Popularity of a law'],0],
['r_ai','ai',4,'A machine-learning model mainly learns by…',['Memorizing every page as a perfect answer','Adjusting parameters from data to improve an objective','Becoming conscious','Eliminating algorithms'],1],
['r_eng','engineering',4,'Engineering design usually involves…',['Ignoring constraints','Balancing requirements, constraints, tradeoffs, testing, and iteration','Only drawing blueprints','Avoiding measurement'],1],
['r_trade','trades_mechanical',4,'In a typical house, the building envelope primarily separates…',['Conditioned interior from exterior environment','Plumbing from electricity only','Roof from framing','Owners from contractors'],0],
['r_psych','psychology',4,'Seeking information that supports an existing belief is…',['Confirmation bias','Homeostasis','Natural selection','Opportunity cost'],0],
['r_soc','sociology',4,'Sociology mainly studies…',['Only brain chemistry','Groups, institutions, structures, and relationships','Planetary motion','Chemical bonds'],1],
['r_rel','religion_culture',4,'Comparative religion is best approached by…',['Treating traditions as identical','Studying beliefs, practices, histories, institutions, and internal diversity','Proving one tradition scientifically','Ignoring history'],1],
['r_lit','literature',4,'A literary theme is…',['Only the title','A recurring central idea or concern','Page count','A spelling rule'],1],
['r_art','art_music',4,'Perspective in visual art commonly represents…',['Depth and spatial relationships','Sound frequency','Taxes','pH'],0],
['r_earth','earth_science',4,'Plate tectonics helps explain…',['Earthquakes, mountains, continental movement','Only weather','Moon phases','Genetics'],0],
['r_astro','astronomy',4,'A light-year measures…',['Time','Distance','Brightness','Mass'],1],
['r_energy','energy',4,'Electrical power is commonly measured in…',['Watts','Pascals','Meters','Kelvin'],0]
];
const OPEN=[
['oe1','reasoning','Two explanations fit an event. One requires three evidence-supported assumptions; another requires fifteen, several unsupported. Does that prove the first is true? Explain.'],
['oe2','geopolitics','A country discovers a huge amount of easily accessible oil. Describe several possible economic, political, international, technological, or social consequences.'],
['oe3','statistics','Explain the difference between correlation and causation. Give an example if you can.'],
['oe4','learning','Choose something you understand well from work, life, or a hobby. Explain it to a smart beginner.'],
['oe5','future','If you invest 30 minutes a day in learning for five years, what do you want to understand, do, or discuss by then?']
];

function show(v){VIEWS.forEach(x=>$(x).classList.toggle('hidden',x!==v))}
function mode(m){authMode=m;$('nameRow').classList.toggle('hidden',m==='login');$('authButton').textContent=m==='login'?'Log in':'Create account';$('signupTab').classList.toggle('active',m==='signup');$('loginTab').classList.toggle('active',m==='login')}
$('signupTab').onclick=()=>mode('signup');$('loginTab').onclick=()=>mode('login');
$('authForm').onsubmit=async e=>{e.preventDefault();$('authMessage').textContent='Working…';let r=authMode==='signup'?await db.auth.signUp({email:$('email').value,password:$('password').value,options:{data:{display_name:$('name').value},emailRedirectTo:location.origin+location.pathname}}):await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(r.error){$('authMessage').textContent=r.error.message;return}if(!r.data.session){$('authMessage').textContent='Check your email to confirm your account, then return here.';return}$('authMessage').textContent='Signed in.';boot()};
$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};

$('interests').innerHTML=EXTRA.map(x=>`<button type="button" class="chip" data-v="${x}">${x}</button>`).join('');
$('interests').onclick=e=>{if(e.target.classList.contains('chip'))e.target.classList.toggle('active')};
$('onboardingForm').onsubmit=async e=>{e.preventDefault();let chosen=[...document.querySelectorAll('.chip.active')].map(x=>x.dataset.v);let r=await db.from('profiles').update({daily_minutes:+$('minutes').value,days_per_week:+$('days').value,onboarding_complete:true,updated_at:new Date().toISOString()}).eq('user_id',user.id);if(r.error)return alert(r.error.message);if(chosen.length)await db.from('user_interests').upsert(chosen.map(s=>({user_id:user.id,subject_key:s,depth_preference:'deep'})),{onConflict:'user_id,subject_key'});profile={...profile,daily_minutes:+$('minutes').value,days_per_week:+$('days').value,onboarding_complete:true};assessmentLanding()};

async function assessmentLanding(){let r=await db.from('placement_attempts').select('*').eq('user_id',user.id).eq('version','v0.4').eq('status','in_progress').order('started_at',{ascending:false}).limit(1);let saved=r.data?.[0];$('resumeAssessment').classList.toggle('hidden',!saved);$('resumeAssessment').dataset.id=saved?.id||'';show('assessmentIntro')}
$('startAssessment').onclick=()=>startAssessment(false);$('resumeAssessment').onclick=()=>startAssessment(true);

async function startAssessment(resume){if(resume){attempt=$('resumeAssessment').dataset.id;let a=await db.from('placement_attempts').select('*').eq('id',attempt).single();round=a.data.current_round||1;let r=await db.from('placement_responses').select('*').eq('attempt_id',attempt).order('answered_at');answers=r.data||[];qIndex=answers.filter(x=>x.round_number===round).length}else{let r=await db.from('placement_attempts').insert({user_id:user.id,version:'v0.4',status:'in_progress',current_round:1}).select().single();if(r.error)return alert(r.error.message);attempt=r.data.id;round=1;qIndex=0;answers=[]}buildRound();show('assessment');renderQ()}
function score(subject){let a=answers.filter(x=>x.subject_key===subject&&x.item_type==='multiple_choice');return a.length?a.filter(x=>x.is_correct).length/a.length:null}
function buildRound(){if(round===1)roundQs=A;else if(round===2)roundQs=A.map(x=>(score(x[1])??0)>=.67?HARD[x[1]]:EASY.find(e=>e[1]===x[1]));else if(round===3)roundQs=R3}
function mcCount(){return answers.filter(x=>x.item_type==='multiple_choice').length}
function renderQ(){if(round>3)return renderOpen();let x=roundQs[qIndex];$('roundLabel').textContent=`ROUND ${round} OF 3`;$('assessmentTitle').textContent='Placement Assessment';$('questionProgress').textContent=`Question ${qIndex+1} of 15`;$('assessmentProgressBar').style.width=`${mcCount()/45*90}%`;$('questionBox').innerHTML=`<div class="eyebrow">${x[1].replaceAll('_',' ')} • difficulty ${x[2]}/10</div><h3>${x[3]}</h3>${x[4].map((o,i)=>`<button class="answer" data-a="${i}">${o}</button>`).join('')}<button class="answer" data-a="-1">I don’t know</button>`}
$('questionBox').onclick=async e=>{if(!e.target.classList.contains('answer'))return;let x=roundQs[qIndex],sel=+e.target.dataset.a,ok=sel===x[5];let row={attempt_id:attempt,user_id:user.id,question_key:x[0],subject_key:x[1],concept_key:null,difficulty:x[2],selected_answer:sel<0?'idk':String(sel),is_correct:sel<0?false:ok,round_number:round,item_type:'multiple_choice'};let r=await db.from('placement_responses').insert(row).select().single();if(r.error)return alert(r.error.message);answers.push(r.data);qIndex++;qIndex<15?renderQ():checkpoint()};
async function checkpoint(){await db.from('placement_attempts').update({current_round:round+1,paused_at:null}).eq('id',attempt);let ra=answers.filter(x=>x.round_number===round&&x.item_type==='multiple_choice'),c=ra.filter(x=>x.is_correct).length;let copy=[['Atlas has a first outline.','The next round will go deeper where you showed strength and keep sampling where Atlas is uncertain.'],['Your map is getting sharper.','One more broad round will test areas outside the basic academic core.'],['The broad scan is complete.','Five final prompts will sample how you reason, explain, and connect systems.']][round-1];$('checkpointHeadline').textContent=copy[0];$('checkpointMessage').textContent=copy[1];$('checkpointStats').innerHTML=`<span class="chip">${c}/15 correct</span><span class="chip">${mcCount()}/45 complete</span><span class="chip">Progress saved</span>`;$('continueAssessment').textContent=round===3?'Continue to reasoning':'Continue';show('checkpoint')}
$('continueAssessment').onclick=()=>{round++;qIndex=0;if(round<=3){buildRound();show('assessment');renderQ()}else{openIndex=answers.filter(x=>x.item_type==='open_ended').length;show('assessment');renderOpen()}};
async function pause(){await db.from('placement_attempts').update({current_round:round,paused_at:new Date().toISOString()}).eq('id',attempt);assessmentLanding()}
$('pauseAssessment').onclick=pause;$('pauseAtCheckpoint').onclick=pause;
function renderOpen(){let x=OPEN[openIndex];$('roundLabel').textContent='REASONING SAMPLE';$('assessmentTitle').textContent='Five open-ended prompts';$('questionProgress').textContent=`Prompt ${openIndex+1} of 5`;$('assessmentProgressBar').style.width=`${90+openIndex*2}%`;$('questionBox').innerHTML=`<h3>${x[2]}</h3><textarea id="openText" placeholder="Answer in your own words."></textarea><button id="saveOpen" class="primary">Save & continue</button><p class="fineprint">Atlas stores this as reasoning evidence. v0.4 deliberately does not fake an automatic open-ended score.</p>`;$('saveOpen').onclick=saveOpen}
async function saveOpen(){let x=OPEN[openIndex],text=$('openText').value.trim();if(text.length<20)return alert('Give Atlas a little more to work with.');let r=await db.from('placement_responses').insert({attempt_id:attempt,user_id:user.id,question_key:x[0],subject_key:x[1],response_text:text,difficulty:5,round_number:4,item_type:'open_ended'}).select().single();if(r.error)return alert(r.error.message);answers.push(r.data);openIndex++;openIndex<5?renderOpen():finishAssessment()}
async function finishAssessment(){let out=[];let keys=[...new Set(answers.filter(x=>x.item_type==='multiple_choice').map(x=>x.subject_key))];for(let k of keys){let a=answers.filter(x=>x.subject_key===k&&x.item_type==='multiple_choice');let weighted=a.reduce((t,x)=>t+(x.is_correct?100:0)*(1+(+x.difficulty/10)),0),w=a.reduce((t,x)=>t+1+(+x.difficulty/10),0),raw=weighted/w,est=Math.max(3,Math.min(88,8+raw*.76)),conf=Math.min(72,10+a.length*19);out.push({user_id:user.id,subject_key:k,estimated_level:est,estimate_confidence:conf,questions_answered:a.length,correct_count:a.filter(x=>x.is_correct).length,last_difficulty:a[a.length-1].difficulty,status:a.length>=3?'provisional':'sampling',updated_at:new Date().toISOString()})}let r=await db.from('assessment_state').upsert(out,{onConflict:'user_id,subject_key'});if(r.error)return alert(r.error.message);await db.from('placement_attempts').update({status:'completed',completed_at:new Date().toISOString(),current_round:4}).eq('id',attempt);await db.from('profiles').update({placement_complete:true,placement_version:'v0.4',updated_at:new Date().toISOString()}).eq('user_id',user.id);profile.placement_version='v0.4';loadApp()}

async function loadCore(){let [sub,con,st,se]=await Promise.all([db.from('subjects').select('*').eq('active',true).order('sort_order'),db.from('concepts').select('*').eq('is_core',true),db.from('assessment_state').select('*').eq('user_id',user.id),db.from('study_sessions').select('*').eq('user_id',user.id).order('created_at')]);subjects=sub.data||[];concepts=con.data||[];states=st.data||[];sessions=se.data||[]}
const verified=s=>(+s.estimated_level)*(+s.estimate_confidence)/100;
function getSubject(k){return subjects.find(x=>x.key===k)}
function getFrontier(){let ranked=subjects.map(s=>({s,state:states.find(x=>x.subject_key===s.key)})).filter(x=>x.s.key!=='hvac').sort((a,b)=>{let av=a.state?verified(a.state):0,bv=b.state?verified(b.state):0;return av-bv});let chosen=ranked.find(x=>concepts.some(c=>c.subject_key===x.s.key))||ranked[0];let cs=concepts.filter(c=>c.subject_key===chosen.s.key);frontierConcept=cs[0]||concepts[0];return {subject:chosen.s,state:chosen.state,concept:frontierConcept}}
async function loadApp(){show('app');$('logout').classList.remove('hidden');$('dailyMinutes').textContent=profile.daily_minutes;await loadCore();renderAll()}
function renderAll(){renderMap();renderPortfolio();renderForecast();renderToday();renderFrontier()}
function renderMap(){$('mapItems').innerHTML=subjects.filter(s=>s.key!=='hvac').map(s=>{let st=states.find(x=>x.subject_key===s.key);if(!st)return `<div class="track"><div class="track-head"><span>${s.name}</span><span>Not sampled</span></div><div class="barbg"></div><div class="track-sub">Atlas still needs evidence here.</div></div>`;let v=verified(st),c=+st.estimate_confidence;return `<div class="track"><div class="track-head"><span>${s.name}</span><span>${v.toFixed(0)} verified / 100</span></div><div class="barbg"><div class="bar" style="width:${v}%"></div></div><div class="track-sub"><span>Estimated ability ${(+st.estimated_level).toFixed(0)}</span><span class="${c<35?'confidence-low':'confidence-good'}">Confidence ${c.toFixed(0)}%</span><span>${st.questions_answered} evidence points</span></div></div>`}).join('')}
function renderPortfolio(){let mins=sessions.filter(x=>x.completed).reduce((a,s)=>a+(s.actual_minutes||0),0),v=states.length?states.reduce((a,s)=>a+verified(s),0)/states.length:0,c=states.length?states.reduce((a,s)=>a+(+s.estimate_confidence),0)/states.length:0;$('lifetimeHours').textContent=(mins/60).toFixed(1);$('verifiedIndex').textContent=v.toFixed(0);$('overallConfidence').textContent=c.toFixed(0)+'%';$('domainsSampled').textContent=`${states.length} / ${subjects.length}`;$('portfolioIndex').textContent=`Portfolio ${v.toFixed(0)}/100`;let gs={};subjects.forEach(s=>{let g=s.group_key||'other';gs[g]=gs[g]||[];gs[g].push(s.key)});$('portfolioGroups').innerHTML=Object.entries(gs).map(([g,keys])=>{let vals=keys.map(k=>states.find(s=>s.subject_key===k)).filter(Boolean).map(verified),gv=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;return `<div class="group-row"><div class="group-head"><span>${g.replaceAll('_',' ')}</span><span>${gv.toFixed(0)}</span></div><div class="barbg"><div class="bar" style="width:${gv}%"></div></div></div>`}).join('')}
function renderForecast(){let w=profile.daily_minutes*profile.days_per_week/60,y=w*52,f=y*5;$('weekly').textContent=w.toFixed(1);$('yearly').textContent=Math.round(y);$('fiveYearHours').textContent=Math.round(f);let cur=states.length?states.reduce((a,s)=>a+verified(s),0)/states.length:1,eff=.48+Math.min(.45,w*.055),pts=[['Now',cur],['6 mo',Math.min(100,cur+Math.sqrt(y*.5)*eff)],['1 yr',Math.min(100,cur+Math.sqrt(y)*eff*1.4)],['3 yr',Math.min(100,cur+Math.sqrt(y*3)*eff*2.0)],['5 yr',Math.min(100,cur+Math.sqrt(y*5)*eff*2.45)]];$('forecastText').textContent=`At your current schedule, Atlas models about ${Math.round(y)} deliberate learning hours per year. Early returns build foundations; later returns can compound as knowledge becomes more connected.`;$('forecastChart').innerHTML=pts.map(([l,v])=>`<div class="forecast-col"><b>${v.toFixed(0)}</b><div class="forecast-bar" style="height:${Math.max(4,v)}%"></div><span>${l}</span></div>`).join('');$('forecastMilestones').innerHTML=[['6 months','Noticeable gaps closing and a sharper personal map.'],['1 year','Broad literacy across substantially more than school basics.'],['3 years','A connected interdisciplinary base with emerging depth tracks.'],['5 years','Potential for unusually broad competence plus expert-level depth in selected domains.']].map(([a,b])=>`<div class="milestone"><strong>${a}</strong><span>${b}</span></div>`).join('')}
function renderToday(){let now=new Date(),m=sessions.filter(s=>s.completed&&new Date(s.completed_at||s.created_at).getMonth()===now.getMonth()&&new Date(s.completed_at||s.created_at).getFullYear()===now.getFullYear()).reduce((a,s)=>a+(s.actual_minutes||0),0);$('monthMinutes').textContent=m;let f=getFrontier();$('todaySummary').textContent=`Atlas is currently allocating new learning toward ${f.subject?.name||'your weakest sampled area'} while preserving review and application.`;let tasks=[['review','Retrieval review','Recall before rereading.'],['lesson',`Frontier lesson: ${f.concept?.name||'core concept'}`,'Learn just beyond your current boundary.'],['application','Application','Use it in a real system or decision.'],['challenge','Stretch challenge','Push above comfortable recognition.']];$('todayItems').innerHTML=tasks.map(([id,t,s])=>`<button class="task ${todayDone.has(id)?'done':''}" data-task="${id}"><div><strong>${t}</strong><small>${s}</small></div><span>${todayDone.has(id)?'✓':'›'}</span></button>`).join('');$('sessionDone').textContent=`${todayDone.size} / 4 complete`;document.querySelectorAll('.task').forEach(b=>b.onclick=()=>openTask(b.dataset.task))}
function renderFrontier(){let f=getFrontier(),st=f.state;$('frontierCard').innerHTML=`<div class="eyebrow">${f.subject?.name||'Frontier'}</div><strong>${f.concept?.name||'Next concept'}</strong><p>${f.concept?.description||''}</p><div class="track-sub"><span>Estimated ability: ${st?(+st.estimated_level).toFixed(0):'unknown'}</span><span>Confidence: ${st?(+st.estimate_confidence).toFixed(0)+'%':'low'}</span><span>Target difficulty: ${targetDifficulty(st)}/10</span></div>`}
function targetDifficulty(st){if(!st)return 3;return Math.max(2,Math.min(9,Math.round((+st.estimated_level)/12)))}
async function ai(mode){let f=getFrontier(),st=f.state;$('aiOutput').classList.remove('hidden');$('aiOutput').innerHTML='<p>Building your next learning object…</p>';let {data,error}=await db.functions.invoke('atlas-ai-content',{body:{mode,subject:f.subject?.name,concept:f.concept?.name,difficulty:targetDifficulty(st),estimated_level:st?.estimated_level,estimate_confidence:st?.estimate_confidence,minutes:Math.max(8,Math.round(profile.daily_minutes*.55))}});if(error){$('aiOutput').innerHTML=`<p>Content engine error: ${error.message}</p>`;return}renderAI(data)}
function renderAI(d){$('aiOutput').innerHTML=`<div class="eyebrow">${d.provider==='atlas_fallback'?'ADAPTIVE ENGINE':'AI-GENERATED'}</div><h3>${d.title}</h3><p><strong>Objective:</strong> ${d.objective}</p><div class="ai-section"><p>${d.explanation}</p></div><div class="ai-section"><strong>Example</strong><p>${d.example}</p></div><div class="ai-section"><strong>Challenge</strong><p>${d.challenge}</p></div><div class="ai-section"><strong>Quick check</strong><p>${d.quiz?.prompt||''}</p>${(d.quiz?.options||[]).map((x,i)=>`<button class="answer aiQuiz" data-i="${i}" data-correct="${d.quiz.correct_index}">${x}</button>`).join('')}<p id="aiQuizMsg"></p></div>${d.note?`<p class="fineprint">${d.note}</p>`:''}`;document.querySelectorAll('.aiQuiz').forEach(b=>b.onclick=()=>{$('aiQuizMsg').textContent=+b.dataset.i===+b.dataset.correct?'Correct — that is evidence of transfer, not just recognition.':'Not quite. Re-read the mechanism and try again.'})}
document.querySelectorAll('.aiAction').forEach(b=>b.onclick=()=>ai(b.dataset.mode));

async function openTask(type){let f=getFrontier(),st=f.state;if(type==='lesson'||type==='challenge'||type==='application'){let {data,error}=await db.functions.invoke('atlas-ai-content',{body:{mode:type==='application'?'application':type,subject:f.subject?.name,concept:f.concept?.name,difficulty:targetDifficulty(st),estimated_level:st?.estimated_level,estimate_confidence:st?.estimate_confidence,minutes:Math.max(8,Math.round(profile.daily_minutes/4))}});if(error)return alert(error.message);$('modalBody').innerHTML=`<div class="eyebrow">${f.subject?.name||''}</div><h2>${data.title}</h2><p>${data.explanation}</p><div class="frontier-card"><strong>${type==='application'?'Application':'Challenge'}</strong><p>${type==='application'?data.example:data.challenge}</p></div><button id="taskDone" class="primary">Mark block complete</button>`;$('taskDone').onclick=()=>completeTask(type,f.concept)}else{$('modalBody').innerHTML=`<div class="eyebrow">RETRIEVAL</div><h2>${f.concept?.name}</h2><p>Before looking anything up, write what you remember and what still feels uncertain.</p><textarea id="retrieveText"></textarea><button id="taskDone" class="primary">Save retrieval</button>`;$('taskDone').onclick=()=>completeTask(type,f.concept)}$('modal').classList.remove('hidden')}
$('closeModal').onclick=()=>$('modal').classList.add('hidden');
async function completeTask(type,concept){todayDone.add(type);if(concept?.key)await db.from('mastery_evidence').insert({user_id:user.id,concept_key:concept.key,source_type:type==='application'?'assignment':type==='review'?'review':type==='challenge'?'quiz':'lesson',source_id:`v04_${type}_${Date.now()}`,score:type==='challenge'?82:72,difficulty:targetDifficulty(states.find(s=>s.subject_key===concept.subject_key)),weight:1});$('modal').classList.add('hidden');renderToday();if(todayDone.size===4){let r=await db.from('study_sessions').insert({user_id:user.id,planned_minutes:profile.daily_minutes,actual_minutes:profile.daily_minutes,session_type:'mixed',completed:true,completed_at:new Date().toISOString()});if(!r.error){todayDone.clear();await loadCore();renderAll();alert('Deposit complete. Today’s learning was added to your knowledge portfolio.')}}}

$('sendFeedback').onclick=async()=>{let r=await db.from('tester_feedback').insert({user_id:user.id,page_key:'v0.4',feedback_type:$('feedbackType').value,message:$('feedbackText').value});$('feedbackMessage').textContent=r.error?r.error.message:'Thanks — feedback saved.';if(!r.error)$('feedbackText').value=''};
document.querySelectorAll('.main-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.main-nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('hidden',x.id!==b.dataset.page))});

async function boot(){let u=(await db.auth.getUser()).data.user;if(!u){$('logout').classList.add('hidden');show('auth');return}user=u;$('logout').classList.remove('hidden');let r=await db.from('profiles').select('*').eq('user_id',u.id).single();if(r.error){$('authMessage').textContent='Profile load failed: '+r.error.message;show('auth');return}profile=r.data;if(!profile.onboarding_complete){$('minutes').value=profile.daily_minutes;$('days').value=profile.days_per_week;show('onboarding');return}if(profile.placement_version!=='v0.4'){assessmentLanding();return}loadApp()}
mode('signup');boot();